# Use this file to store passwords to services that your server you use. When
# the server starts, the passwords will be automatically loaded and can be
# accessed from the `session.passwords` field. If you don't have access to a
# session object, passwords can also be accessed from
# `Serverpod.instance.passwords`. You can provide different passwords for
# different run configurations. If you want the same password for any
# configuration used, place it under `shared`.
#
# Note that this file should not be under version control. Store it in a safe
# place.

# Save passwords used across all configurations here.
shared:
  mySharedPassword: 'my password'

# These are passwords used when running the server locally in development mode
development:
  database: 'sabbir'
  redis: 't_i_G4cg1vslUzq53tXzkQw5FneFQmSe'

  # The service secret is used to communicate between servers and to access the
  # service protocol.
  serviceSecret: 'QEhLB-UYbCQcPpCE4ju70RDjvVbbuW8Z'

test:
  database: 'cSr1GztdW4OnpXFnNLJ6X91IEB4xbkqN'
  redis: 'xte_WFejuLWFZi1t3e9Lq48-gkTytkM5'

# Passwords used in your staging environment if you use one. The default setup
# use a password for Redis.
staging:
  database: 'xlvyuDzXYmiFiV-UM7Nqg6uqrPtUOWXI'
  serviceSecret: '8oUnixoRaKPG898ZS8Jh5tjE2-96RMPo'

# Passwords used in production mode.
production:
  database: 'zhOpsgUhsImyPyVcYCrjMrnoVjmaYkBO'
  serviceSecret: 'in2bgt2TcU5rzwTYEbqQ0Q_K8Z7FGbpP'
